[build]
  publish = "_site"
  command = "npx @11ty/eleventy"

# Deja que Identity maneje sus rutas
[[redirects]]
  from = "/.netlify/*"
  to = "/.netlify/:splat"
  status = 200

# Siempre cargar el CMS desde admin/
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Todo lo demás → home
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

