[build]
  publish = "_site"
  command = "npm run build"

# Redirección para TinaCMS admin
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Redirección general
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
